src/med/system/entity/Consulta.java
package med.system.entity;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Consulta implements Bean {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name="id", nullable=false, unique=true)
    private Long id;
    
    @Column(name="data_consulta", nullable=false, unique=false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date dataConsulta;
    
    @Column(name="titulo", nullable=false, unique=false)
    private String titulo;
    
    @Column(name="observacoes", nullable=false, unique=false)
    private String observacoes;
    
    @ManyToOne
    private Usuario paciente;
    
    @ManyToOne
    private Doutor doutor;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getDataConsulta() {
        return dataConsulta;
    }

    public void setDataConsulta(Date dataConsulta) {
        this.dataConsulta = dataConsulta;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getObservacoes() {
        return observacoes;
    }

    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    public Usuario getPaciente() {
        return paciente;
    }

    public void setPaciente(Usuario paciente) {
        this.paciente = paciente;
    }

    public Doutor getDoutor() {
        return doutor;
    }

    public void setDoutor(Doutor doutor) {
        this.doutor = doutor;
    }
    
}

src/med/system/controller/ConsultaBean.java
package med.system.controller;

import java.io.IOException;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import med.system.dao.ConsultaDAO;
import med.system.entity.Consulta;

@SessionScoped
@ManagedBean(name = "consultaBean")
public class ConsultaBean {
    
    private Consulta consulta = new Consulta();
    private ConsultaDAO consultaDao = new ConsultaDAO();
    
    public void exclui(Consulta consulta) throws IOException {
        this.consultaDao.remove(consulta);
        goListPage();
    }
    
    public List<Consulta> getConsultas() {
        return this.consultaDao.listaTodos();
    }
    
    public void salva() throws IOException {
        if (isFilledFields(this.consulta)) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "ERRO!", "Informe os dados corretamente."));
        } else {
            this.consultaDao.salva(this.consulta);
            this.consulta = new Consulta();

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "SUCESSO!", "Consulta agendada com sucesso!"));
            FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
            goListPage();
        }
    }
    
    public void update(Consulta consulta) throws IOException {
        this.consulta = consulta;
        goUpdatePage();
    }
    
    private boolean isFilledFields(Consulta consulta) {
        return consulta.getTitulo().isEmpty() || consulta.getDataConsulta() == null || consulta.getDoutor() == null || consulta.getPaciente() == null;
    }
    
    public void goUpdatePage() throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("update.xhtml");
    }
    
    public void goListPage() throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("list-per-patient.xhtml");
    }

    public Consulta getConsulta() {
        return consulta;
    }

    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    
}

src/med/system/controller/DoutorBean.java
package med.system.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import med.system.dao.DoutorDAO;
import med.system.entity.Doutor;

@ManagedBean(name = "doutorBean")
public class DoutorBean {
    
    private Doutor doutor = new Doutor();
    private DoutorDAO doutorDao = new DoutorDAO();
    
    public void exclui(Doutor doutor) throws IOException {
        this.doutorDao.remove(doutor);
        goListPage();
    }
    
    public List<Doutor> getDoutores() {
        return this.doutorDao.listaTodos();
    }
    
    public List<SelectItem> getDoutoresSelectedItem() {
        List<Doutor> listaDoutores = this.doutorDao.listaTodos();
        List<SelectItem> itens = new ArrayList<SelectItem>(listaDoutores.size());
        for (Doutor i : listaDoutores) {
            itens.add(new SelectItem(i.getId(), i.getNome()));
        }
        return itens;
    }
    
    public void salva() throws IOException {
        if (isFilledFields(this.doutor)) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "ERRO!", "Informe os dados corretamente."));
        } else {
            this.doutorDao.salva(this.doutor);
            this.doutor = new Doutor();

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "SUCESSO!", "Doutor registrado com sucesso!"));
            FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
            goListPage();
        }
    }
    
    private boolean isFilledFields(Doutor doutor) {
        return doutor.getNome().isEmpty() || doutor.getFaixaIdade().isEmpty();
    }
    
    public void goMainPage() throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("../main.xhtml");
    }
    
    public void goListPage() throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("consult.xhtml");
    }

    public Doutor getDoutor() {
        return doutor;
    }

    public void setDoutor(Doutor doutor) {
        this.doutor = doutor;
    }
}

WebContent/consultas/create.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	
<h:head>
	<title>Agendar consulta - MedSystem</title>
	<link rel="stylesheet" type="text/css" href="../resources/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/template.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/faces.css" />
</h:head>

<h:body>
	<div class="geral">
		<ui:include src="../WEB-INF/comuns/header.xhtml" />
		<h:form>
			<div class="form-group"><h2><span class="glyphicon glyphicon-pencil"></span> Agendar consulta</h2></div>
			<hr />
			
			<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
			
			<div class="row">
		        <div class="form-group col-xs-6">
		            <label for="titulo">Titulo:</label> 
		            <h:inputText styleClass="form-control" id="tituloConsulta" value="#{consultaBean.consulta.titulo}" />
		            <p:watermark for="tituloConsulta" value="Titulo da consulta" id="watermarkTitulo" />
		        </div>
		        <div class="form-group col-xs-3">
		        	<label for="dataConsulta">Data Consulta:</label> 
		            <h:inputText styleClass="form-control" id="dataConsulta" value="#{consultaBean.consulta.dataConsulta}">
		            	<f:convertDateTime pattern="dd/MM/yyyy" />
		            </h:inputText>
		            <p:watermark for="dataConsulta" value="Data da consulta" id="watermarkData" />
		        </div>
		    </div>
		
		    <div class="row">
				<div class="form-group col-xs-3">
		            <label for="doutor">Doutor:</label>
		            <h:selectOneMenu id="doutor" value="#{consultaBean.consulta.doutor}" label="doutor" 
		            	converter="entityConverter" styleClass="form-control" items="#{doutorBean.doutoresSelectedItem}">
						<f:selectItem itemValue="" itemLabel="Selecione..." />
						<f:selectItems var="doutor" value="#{doutorBean.doutores}" itemValue="#{doutor}" itemLabel="#{doutor.nome}" />
					</h:selectOneMenu>
		        </div>
		        <div class="form-group col-xs-6">
		            <label for="comboRule">Paciente:</label>
		            <h:selectOneMenu id="paciente" value="#{consultaBean.consulta.paciente}" label="paciente" 
           				converter="entityConverter" styleClass="form-control" items="#{usuarioBean.patient}">
						<f:selectItems var="paciente" value="#{usuarioBean.usuarios}" itemValue="#{paciente}" itemLabel="#{paciente.nome}" />
					</h:selectOneMenu>
		        </div>  
		    </div>

		    <div class="row">
		    	<div class="form-group col-xs-9">
		    		<label for="Observacoes">Observações:</label>
		    		<h:inputTextarea styleClass="form-control" id="obs" value="#{consultaBean.consulta.observacoes}" />
		    	</div>
		    </div>
		    
		    <div class="form-group">
		        <p:commandButton styleClass="btn btn-success" value="Salvar" icon="ui-icon-circle-plus" actionListener="#{consultaBean.salva}" />
		        <p:commandButton styleClass="btn btn-default" data-dismiss="modal" value="Voltar" actionListener="#{doutorBean.goMainPage}"/>
		    </div>
		</h:form>
		
		<ui:include src="../WEB-INF/comuns/modal.xhtml" />
		<div class="footer">
			<ui:include src="../WEB-INF/comuns/footer.xhtml" />
		</div>
	</div>
</h:body>
</html>

WebContent/consultas/list-per-patient.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	
<h:head>
	<title>Minhas Consultas - MedSystem</title>
	<link rel="stylesheet" type="text/css" href="../resources/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/template.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/faces.css" />
</h:head>

<h:body>
	<div class="geral">
		<ui:include src="../WEB-INF/comuns/header.xhtml" />
		<h:form>
			<div class="container-fluid">
	            <h1>Minhas Consultas</h1>
	            <div class="row">
	                <div class="col-lg-6">
	                    <div class="input-group">
	                        <p>
	                            <a href="create.xhtml" data-toggle="modal" data-target="#util-modal"  class="btn btn-primary">
	                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
	                            </a>
	                        </p>
	                    </div>
	                </div>
	            </div>
	
				<p:dataTable id="grid-basic" styleClass="table table-condensed table-hover table-striped" value="#{consultaBean.consultas}" 
					var="consulta" paginator="true" rows="9" lazy="true">
					<p:column>
						<f:facet name="header">
							<h:outputText value="ID" />
						</f:facet>
						<h:outputText value="#{consulta.id}" />
					</p:column>
					
					<p:column>
						<f:facet name="header">
							<h:outputText value="Assunto" />
						</f:facet>
						<h:outputText value="#{consulta.titulo}" />
					</p:column>
					
					<p:column>
						<f:facet name="header">
							<h:outputText value="Data" />
						</f:facet>
						<h:outputText value="#{consulta.dataConsulta}" />
					</p:column>
					
					<p:column>
						<f:facet name="header">
							<h:outputText value="Paciente" />
						</f:facet>
						<h:outputText value="#{consulta.paciente.nome}" />
					</p:column>
					
					<p:column>
						<f:facet name="header">
							<h:outputText value="Doutor" />
						</f:facet>
						<h:outputText value="#{consulta.doutor.nome}" />
					</p:column>
					
					<p:column>
						<p:tooltip />
						<p:commandButton icon="ui-icon-pencil" action="#{consultaBean.update(consulta)}" />
					</p:column>
					
					<p:column>
						<p:tooltip />
						<p:commandButton icon="ui-icon-circle-close" actionListener="#{consultaBean.exclui(consulta)}" />
					</p:column>
				</p:dataTable>
				
				<div class="form-group">
			    	<p:tooltip />
			        <p:commandButton styleClass="btn btn-default" data-dismiss="modal" value="Voltar" action="#{doutorBean.goMainPage}"/>
			        <p:separator />
			    </div>
        	</div>
		</h:form>
		
		<ui:include src="../WEB-INF/comuns/modal.xhtml" />
		<div class="footer">
			<ui:include src="../WEB-INF/comuns/footer.xhtml" />
		</div>
	</div>
</h:body>
</html>

WebContent/consultas/list.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	
<h:head>
	<title>Consultas Agendadas - MedSystem</title>
	<link rel="stylesheet" type="text/css" href="../resources/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/template.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/faces.css" />
</h:head>

<h:body>
	<div class="geral">
		<ui:include src="../WEB-INF/comuns/header.xhtml" />
		<h:form>
			<div class="container-fluid">
	            <h1>Consultas agendadas</h1>
	            <div class="row">
	                <div class="col-lg-6">
	                    <div class="input-group">
	                        <p>
	                            <a href="create.xhtml" data-toggle="modal" data-target="#util-modal"  class="btn btn-primary">
	                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
	                            </a>
	                        </p>
	                    </div>
	                </div>
	            </div>
	
				<h:dataTable id="grid-basic" styleClass="table table-condensed table-hover table-striped" value="#{consultaBean.consultas}" var="item">
					<h:column>
						<f:facet name="header">
							<h:outputText value="Assunto" />
						</f:facet>
						<h:outputText value="#{item.titulo}" />
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:outputText value="Data" />
						</f:facet>
						<h:outputText value="#{item.dataConsulta}" />
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:outputText value="Paciente" />
						</f:facet>
						<h:outputText value="#{item.paciente}" />
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:outputText value="Doutor" />
						</f:facet>
						<h:outputText value="#{item.doutor}" />
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:commandButton icon="glyphicon glyphicon-remove" styleClass="btn btn-danger" />
						</f:facet>
					</h:column>
				</h:dataTable>
        	</div>
		</h:form>
		
		<ui:include src="../WEB-INF/comuns/modal.xhtml" />
		<div class="footer">
			<ui:include src="../WEB-INF/comuns/footer.xhtml" />
		</div>
	</div>
</h:body>
</html>

WebContent/consultas/update.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	
<h:head>
	<title>Editar consulta - MedSystem</title>
	<link rel="stylesheet" type="text/css" href="../resources/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/template.css" />
	<link rel="stylesheet" type="text/css" href="../resources/css/faces.css" />
</h:head>

<h:body>
	<div class="geral">
		<ui:include src="../WEB-INF/comuns/header.xhtml" />
		<h:form>
			<div class="form-group"><h2><span class="glyphicon glyphicon-pencil"></span> Editar consulta</h2></div>
			<hr />
			
			<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
			
			<div class="row">
				<div class="form-group col-xs-1">
					<label for="titulo">ID:</label>
					<h:outputText styleClass="form-control" id="idConsulta"
						value="#{consultaBean.consulta.id}" />
				</div>
			</div>

			<div class="row">
		        <div class="form-group col-xs-6">
		            <label for="titulo">Titulo:</label> 
		            <h:inputText styleClass="form-control" id="tituloConsulta" value="#{consultaBean.consulta.titulo}" />
		        </div>
		        <div class="form-group col-xs-3">
		        	<label for="dataConsulta">Data Consulta:</label> 
		            <h:inputText styleClass="form-control" id="dataConsulta" value="#{consultaBean.consulta.dataConsulta}">
		            	<f:convertDateTime pattern="dd/MM/yyyy" />
		            </h:inputText>
		        </div>
		    </div>
		
		    <div class="row">
				<div class="form-group col-xs-3">
		            <label for="doutor">Doutor:</label>
		            <h:selectOneMenu id="doutor" value="#{consultaBean.consulta.doutor}" label="doutor" 
		            	converter="entityConverter" styleClass="form-control" items="#{doutorBean.doutoresSelectedItem}">
						<f:selectItem itemValue="" itemLabel="Selecione..." />
						<f:selectItems var="doutor" value="#{doutorBean.doutores}" itemValue="#{doutor}" itemLabel="#{doutor.nome}" />
					</h:selectOneMenu>
		        </div>
		        <div class="form-group col-xs-6">
		            <label for="comboRule">Paciente:</label>
		            <h:selectOneMenu id="paciente" value="#{consultaBean.consulta.paciente}" label="paciente" 
           				converter="entityConverter" styleClass="form-control" items="#{usuarioBean.patient}">
						<f:selectItems var="paciente" value="#{usuarioBean.usuarios}" itemValue="#{paciente}" itemLabel="#{paciente.nome}" />
					</h:selectOneMenu>
		        </div>  
		    </div>

		    <div class="row">
		    	<div class="form-group col-xs-9">
		    		<label for="Observacoes">Observações:</label>
		    		<h:inputTextarea styleClass="form-control" id="obs" value="#{consultaBean.consulta.observacoes}" />
		    	</div>
		    </div>
		    
		    <div class="form-group">
		    	<p:tooltip />
		        <p:commandButton styleClass="btn btn-success" value="Salvar" icon="ui-icon-circle-plus" action="#{consultaBean.salva}" />
		        <p:commandButton styleClass="btn btn-default" data-dismiss="modal" value="Voltar" action="#{consultaBean.goListPage}"/>
		        <p:separator />
		    </div>
		</h:form>
		
		<ui:include src="../WEB-INF/comuns/modal.xhtml" />
		<div class="footer">
			<ui:include src="../WEB-INF/comuns/footer.xhtml" />
		</div>
	</div>
</h:body>
</html>